### ISSUE TITLE
Code generator

### ISSUE THREAD

**Issue by joeblew99** [nubank/i18next#3]
This lib seems to use untyped access ?
No code generation support off the JSON ?

**Comment by williamhjcho** [comment]
Unfortunately no, at least for now.
The main idea here was to be as self-contained as possible, this is also why there are multiple (flutter-level) interfaces for inserting your own custom implementations and configurations.

In the case of JSON deserialization, as is, it is necessary to use the `I18NextLocalizationDelegate` (please take a look at the README and code docs).
Also, since deserialization can be done in multiple ways, it was deferred to the implementer's preferred choice.
