### ISSUE TITLE
Not able to style variables

### ISSUE THREAD

**Issue by Ahmadre** [nubank/i18next#32]
I have an example where I want to show the email inside the translation, but with bold fontWeight.

Til now it's not possible to style variables which are interpolated `{{ email }}`.

Can we have this feature?

**Comment by Ahmadre** [comment]
I found a solution:

https://github.com/samuelezedi/linkwell

But maybe you're interested in styling anyway :)

**Comment by williamhjcho** [comment]
This package is just for dealing with pure strings, maybe you could use a formatting option for styling that is defined on the string itself?

From what I got the feature(s) on linkwell match a pattern to a style, right? `i.e. (String) -> TextStyle|TextSpan|Widget`

We do offer some (formatting options)[https://www.i18next.com/translation-function/formatting] so you'd add an interpolation variable + format (e..g `{{email, emailFormat}}`), but it is restricted to a `(String) -> String` format since the output of the translation is done via the `I18next.t` interface.

**Comment by williamhjcho** [comment]
We won't be implementing it for now, since there are great alternatives that could be used in conjunction.
But if the need arises on the future, please feel free to open up this issue again
